// Set current time... Enables remote control to find out when studio was started
window.document.openTimestamp = (new Date()).getTime();
// Set window name if necessary. Makes window accessible via remote control.
if (window.name != "CoreMediaStudio") {
  window.name = "CoreMediaStudio";
}

joo = {
  localization: {
    localeCookieName: "com.coremedia.cms.editor.locale"
  }
};

(function () {
  // http://stackoverflow.com/questions/984510/what-is-my-script-src-url
  var configLocationPath = (function() {
    var scripts = document.getElementsByTagName('script'),
            script = scripts[scripts.length - 1];
    var scriptSrc;
    if (script.getAttribute.length !== undefined) {
      scriptSrc = script.getAttribute('src')
    } else {
      scriptSrc = script.getAttribute('src', 2);
    }

    return scriptSrc + "/..";
  }());

  // var pathToRoot = configLocationPath + "/../";

  var pathname = window.location.pathname;

  var pathSegments = pathname.split("/").length;

  var pathToRoot = "";
  for (var i = 0; i < pathSegments - 1; i++) {
    pathToRoot += "../";
  }

  // TODO Ext6: currently only "studio" contextPath is supported. However, application should not be aware of the deployment
  if (pathname.match(/^\/studio\//, pathname)) {
    pathToRoot += "studio/";
  }

  window.coremediaRemoteServiceUri = pathToRoot + "api/";

  document.write('<script type="text/javascript" src="' + window.coremediaRemoteServiceUri + 'supported-locales.js?jsonp=joo.localization.supportedLocales="></script>');
  document.write('<script type="text/javascript" src="' + window.coremediaRemoteServiceUri + 'accept-language-header.js?jsonp=joo.localization.preferredLocales="></script>');

  // Insert Favicon, generated by http://realfavicongenerator.net/
  document.write('<link rel="apple-touch-icon" sizes="180x180" href="' + configLocationPath + '/apple-touch-icon.png">');
  document.write('<link rel="icon" type="image/png" href="' + configLocationPath + '/favicon-32x32.png" sizes="32x32">');
  document.write('<link rel="icon" type="image/png" href="' + configLocationPath + '/favicon-16x16.png" sizes="16x16">');
  document.write('<link rel="manifest" href="' + configLocationPath + '/manifest.json">');
  document.write('<link rel="mask-icon" href="' + configLocationPath + '/safari-pinned-tab.svg" color="#4189dd">');
  document.write('<link rel="shortcut icon" href="' + configLocationPath + '/favicon.ico">');
  document.write('<meta name="apple-mobile-web-app-title" content="CoreMedia Studio">');
  document.write('<meta name="application-name" content="CoreMedia Studio">');
  document.write('<meta name="msapplication-config" content="' + configLocationPath + '/browserconfig.xml">');
  document.write('<meta name="theme-color" content="#b3b1b1">');
})();
