# START HELPER FUNCTIONS
def local_first_cookbook(name, dir)
  if ::File.exist?(File.join(File.dirname(__FILE__), "#{dir}"))
    cookbook(name, :path => "#{dir}")
  else
    cookbook(name)
  end
end

def add_all_from_dir(dir, excludes = [])
  excludes = excludes + ['chefignore', File.basename(File.dirname(File.expand_path(__FILE__)))]
  cwd = File.dirname(__FILE__)
  cookbooks_dir = File.join(cwd, dir)
  return unless File.exist?(cookbooks_dir)
  Dir.chdir(File.join(cwd, dir))
  Dir.glob('*').each do |cookbook_name|
    cookbook cookbook_name, :path => "#{dir}/#{cookbook_name}" unless excludes.include?(cookbook_name)
  end
  Dir.chdir(cwd)
end

# END HELPER FUNCTIONS
source 'https://supermarket.chef.io'

metadata

group :integration do
  add_all_from_dir '../../thirdparty-cookbooks'
  add_all_from_dir '../../cookbooks'
  # cookbook 'blueprint-dev-tooling', path: '../blueprint-dev-tooling'
end
