import ResourceBundleUtil from "@jangaroo/runtime/l10n/ResourceBundleUtil";
import CatalogStudioPlugin_properties from "./CatalogStudioPlugin_properties";

/**
 * Overrides of ResourceBundle "CatalogStudioPlugin" for Locale "ja".
 * @see CatalogStudioPlugin_properties#INSTANCE
 */
ResourceBundleUtil.override(CatalogStudioPlugin_properties, {
  CMProduct_text: "商品",
  CMProduct_productName_text: "商品タイトル",
  CMProduct_productName_emptyText: "商品のタイトルをこちらに入力",
  CMProduct_productName_toolTip: "商品のタイトル",
  CMProduct_productCode_text: "商品コード",
  CMProduct_productCode_emptyText: "商品のコードをこちらに入力。",
  CMProduct_teaserText_text: "簡単な説明",
  CMProduct_teaserText_emptyText: "商品の簡単な説明をこちらに入力",
  CMProduct_teaserText_toolTip: "商品の簡単な説明",
  CMProduct_detailText_text: "詳細な説明",
  CMProduct_detailText_emptyText: "商品の詳細な説明をこちらに入力",
  CMProduct_detailText_toolTip: "商品の詳細な説明",
  CMProduct_downloads_text: "ダウンロード",
  CMProduct_downloads_emptyText: "こちらのライブラリからドラッグしてダウンロードを割り当て。",
  CMProduct_downloads_toolTip: "商品のダウンロード",
  CMProduct_shortDescription_emptyText: "商品の簡単な説明をこちらに入力。",
  CMProduct_shortDescription_text: "簡単な説明",
  CMProduct_shortDescription_toolTip: "商品の簡単な説明",
  CMProduct_longDescription_text: "詳細な説明",
  CMProduct_longDescription_emptyText: "商品の詳細な説明をこちらに入力",
  CMProduct_longDescription_toolTip: "商品の詳細な説明",
  CMProduct_contexts_text: "カテゴリー",
  CMProduct_contexts_emptyText: "こちらのライブラリからドラッグして商品カテゴリーを割り当て。",
  CMProduct_contexts_toolTip: "商品カテゴリー",
  CMProduct_parentChannel_text: "親カテゴリー",
  CMProduct_parentChannel_emptyText: "こちらのライブラリからドラッグしてカテゴリーを追加。",
  CMCategory_text: "カテゴリー",
  CMCategory_products_text: "商品",
  CMCategory_title_text: "カテゴリーのタイトル",
  CMCategory_title_emptyText: "カテゴリーのタイトルをこちらに入力。",
  CMCategory_title_toolTip: "カテゴリーのタイトル",
  CMCategory_categoryName_text: "カテゴリー名",
  CMCategory_categoryName_emptyText: "カテゴリーの名前をこちらに入力。",
  CMCategory_displayName_text: "表示名",
  CMCategory_teaserText_text: "簡単な説明",
  CMCategory_teaserText_emptyText: "カテゴリーの簡単な説明をこちらに入力。",
  CMCategory_shortDescription_text: "簡単な説明",
  CMCategory_shortDescription_emptyText: "カテゴリーの簡単な説明をこちらに入力。",
  CMCategory_detailText_text: "詳細な説明",
  CMCategory_detailText_emptyText: "カテゴリーの詳細な説明をこちらに入力。",
  CMCategory_parentChannel_text: "親カテゴリー",
  CMCategory_parentChannel_emptyText: "こちらのライブラリからドラッグしてカテゴリーを追加。",
  Catalog_show_all: "すべて",
  CMCategory_no_products_for_picture: "この写真はどの商品からもリンクしていません。",
  CMCategory_no_parent: "このカテゴリーはトップカテゴリーで、親はありません。",
  CMCategory_no_products: "このカテゴリーには商品はありません。",
  Tab_catalog_structure_title: "カタログの構成",
  Corporate_catalog_title: "カタログ",
  ProductAssets_Downloads_label: "ダウンロード",
  PropertyGroup_Assets_label: "資産",
  PropertyGroup_SubCategories_label: "子カテゴリー",
  PropertyGroup_RelatedProducts_label: "関連商品",
  Catalog_show_search_fails_for_Content: "選択したコンテンツは、現在の設定ではライブラリに表示できません。表示するには、プリファレンスでお気に入りのサイトを変更します。",
  catalog_checkout_error_title: "編集カタログのエラー",
  catalog_checkout_error_message: "{0} '{1}' は別のユーザーがチェックアウトしたため、アクションの実行に失敗しました。",
  catalog_copy_or_link_title: "リンクを作成するか、コンテンツアイテムをコピーしますか?",
  catalog_copy_or_link_message: "クリップボード選択が、別のカテゴリーからコピーされました。カテゴリー '{0}' にコピーするかリンクしますか?",
  catalog_undelete_err_title: "コンテンツの復元エラー",
  catalog_undelete_err_message: "'{0}' のリンクの復元に失敗しました。コンテンツが開かれていたので、リンクを手作業で復元できます。",
  Filter_LostAndFound_text: "孤立したカタログアイテム",
  Filter_LostAndFound_checkbox: "孤立したカタログアイテムのみを表示",
  catalog_lists_product_code_column: "商品コード",
});
