name 'blueprint-mysql'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures blueprint-mysql'
long_description 'Installs/Configures blueprint-mysql'
version '1.0.0'

depends 'mysql', '~> 8.0.2'
depends 'yum-mysql-community', '~> 0.3.0'
depends 'blueprint-base'
