[#ftl]
[#-- @implicitly included --]
[#-- @ftlvariable name="cmpage" type="com.coremedia.blueprint.common.contentbeans.Page" --]
[#import "/lib/coremedia.com/cae.ftl" as cm]
[#import "/lib/coremedia.com/preview.ftl" as preview]
[#import "/lib/coremedia.com/blueprint.ftl" as bp]
[#-- additional imports for livecontext and corporate --]
[#import "/lib/coremedia.com/livecontext.ftl" as lc]
[#-- elastic social --]
[#import "/lib/coremedia.com/blueprint/elasticsocial.ftl" as es]
[#-- asset managment download portal --]
[#import "/lib/coremedia.com/blueprint/am.ftl" as am]
