import ResourceBundleUtil from "@jangaroo/runtime/l10n/ResourceBundleUtil";
import ElasticSocialStudioPlugin_properties from "./ElasticSocialStudioPlugin_properties";

/**
 * Overrides of ResourceBundle "ElasticSocialStudioPlugin" for Locale "ja".
 * @see ElasticSocialStudioPlugin_properties#INSTANCE
 */
ResourceBundleUtil.override(ElasticSocialStudioPlugin_properties, {
  CMMail_text: "Eメールテンプレート",
  CMMail_from_text: "送信元",
  CMMail_from_emptyText: "送信者のEメールアドレスをこちらに入力。",
  CMMail_subject_text: "主題",
  CMMail_subject_emptyText: "Eメールの主題をこちらに入力。",
  CMMail_text_text: "Eメールテキスト",
  CMMail_text_emptyText: " ",
  CMMail_contentType_text: "コンテンツのタイプ（テキスト/プレーン、テキスト/html）",
  CMMail_contentType_emptyText: "テキスト/プレーン、テキスト/html",
  CMMail_lang_text: "言語",
  CMMail_lang_emptyText: "言語をこちらへ入力。",
  CMMail_country_text: "国",
  CMMail_country_emptyText: "国をこちらに入力。",
  CMMail_variants_text: "バリエーション",
  CMMail_variants_emptyText: "バリエーションをこちらに入力。",
  ESDynamicList_text: "動的Elastic Socialリスト",
  ESDynamicList_interval_text: "インターバル",
  ESDynamicList_aggregationType_text: "リスト",
  ESDynamicList_channel_text: "コンテキスト",
  cmmail_help_text: "Eメールフォームのヘルプを表示",
  cmmail_help_window_title: "Eメールフォームのヘルプ",
  cmmail_help_window_content: "Eメールフォームで、Eメールでユーザーに表示されるテキストを設定できます。各ユーザーに動的に生成される値を設定できます。値は次のとおりです：",
  cmmail_help_window_value: "値",
  cmmail_help_window_description: "説明",
  cmmail_help_window_value_name: "ユーザーの名前で置換されます。",
  cmmail_help_window_value_givenName: "ユーザーの名で置換されます。",
  cmmail_help_window_value_surName: "ユーザーの姓で置換されます。",
  cmmail_help_window_value_email: "ユーザーのEメールアドレスで置換されます。",
  cmmail_help_window_value_token: "ユーザーの一意のセキュリティトークンで置換されます。",
  cmmail_help_window_value_baseUrl: "パスワードのアクティベーションまたはリセットのリンクで置換されます。",
  cmmail_help_window_value_commentText: "ユーザーのコメントで置換されます（該当する場合）。",
  cmmail_help_window_value_commentDate: "ユーザーのコメントの日付で置換されます（該当する場合）。",
  cmmail_help_window_value_commentUrl: "コメントの返信についてのみ有効。返信を受信した、コメントの付いている記事およびコメントのURLで置換されます（該当する場合）。",
  cmmail_help_window_value_replyText: "ユーザーの返信で置換されます（該当する場合）。",
  cmmail_help_window_value_replyAuthorName: "返信したユーザーの名前で置換されます（該当する場合）。",
  cmmail_help_window_value_replyDate: "ユーザーの返信の日付で置換されます（該当する場合）。",
  curated_content_create_article_button_tooltip: "選択した投稿のコメントテキストから新たな記事を作成",
  curated_content_create_pictures_button_tooltip: "選択した投稿のメディア添付から新たな写真を作成",
  curated_content_create_gallery_button_tooltip: "選択した投稿のメディアからギャラリーを作成",
  btn_close: "閉じる",
  MOST_COMMENTED: "コメント数が最も多い",
  MOST_RATED: "評価数が最も多い",
  MOST_LIKED: "Like数が最も多い",
  MOST_SHARED: "シェア数が最も多い",
  TOP_RATED: "評価が最も高い",
  TOP_REVIEWED: "レビューの評価が最も高い",
  MOST_REVIEWED: "レビューが最も多い",
  INFINITY: "すべて",
  LAST_YEAR: "昨年",
  LAST_MONTH: "先月",
  LAST_WEEK: "先週",
  LAST_DAY: "昨日",
});
