http:
  routers:
    traefik:
      entrypoints:
        - webaccesssecure
        - webaccessinsecure
      rule: Host(`monitor.{{ env "ENVIRONMENT_FQDN" | default "docker.localhost"}}`)
      service: api@internal

