name 'blueprint-postgresql'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures blueprint-postgresql'
long_description 'Installs/Configures blueprint-postgresql'
version '1.0.0'

depends 'blueprint-base'
depends 'blueprint-yum'
depends 'yum-pgdg', '~> 0.2.7'
depends 'postgresql', '~> 4.0.0'
