#!/bin/sh

echo "[DOCKER ENTRYPOINT] - entering $0"
set -e

VERBOSE=""

if [ "${DEBUG_ENTRYPOINT}" = "true" ]; then
  echo "[DOCKER ENTRYPOINT] - DEBUG_ENTRYPOINT detected, all commands will be printed"
  set -x
  VERBOSE="-v"
fi

if [ "${SKIP_PUBLISH}" = "true" ]; then
  echo "[DOCKER ENTRYPOINT] - skipping content publish chain $@"
else

  # do not remove '< /dev/null 2> /dev/null | grep -v groovy\:' - this ensures groovysh exit and only value printing
  PUBLISHED=$(./tools/bin/cm groovysh /coremedia/getSystemTableProperty.groovy -q -DpropKey=content-published < /dev/null 2> /dev/null | grep -v groovy\:)

  echo "[DOCKER ENTRYPOINT] - publishing all content, when import has finished"
  if [ "${PUBLISHED}" != "true"  ] || [ "${FORCE_REIMPORT_CONTENT}" = "true" ]; then
    ./tools/bin/cm bulkpublish -u ${TOOLS_USER} -p ${TOOLS_PASSWORD} -a -b -c 2> /dev/null
    ./tools/bin/cm groovysh /coremedia/setSystemTableProperty.groovy -q -DpropKey=content-published -DpropVal=true < /dev/null &> /dev/null
  else
    echo "[DOCKER ENTRYPOINT] - content already published, skipping ..."
  fi
fi

test $# -gt 0 && exec ./$@ || echo "[DOCKER ENTRYPOINT] - entrypoint chain finished"
