import ResourceBundleUtil from "@jangaroo/runtime/l10n/ResourceBundleUtil";
import TaxonomyStudioPlugin_properties from "./TaxonomyStudioPlugin_properties";

/**
 * Overrides of ResourceBundle "TaxonomyStudioPlugin" for Locale "ja".
 * @see TaxonomyStudioPlugin_properties#INSTANCE
 */
ResourceBundleUtil.override(TaxonomyStudioPlugin_properties, {
  TaxonomySearch_empty_text: "タグの候補を入力してください",
  TaxonomySearch_empty_linklist_text: "タグを入力するか、こちらに候補をドラッグアンドドロップしてください。",
  TaxonomySearch_empty_search_text: "検索…",
  TaxonomySearch_loading_text: "ロード中…",
  TaxonomySearch_no_hit: "検索結果がありません。",
  TaxonomyEditor_deletion_blocked_text: "選択したタグまたはその子は、{0}コンテンツにリンクしています。このリンクは、選択したタグを削除する前に、手作業で削除する必要があります。",
  TaxonomyEditor_deletion_failed_text: "タグの削除に失敗しました：{0}<br><br>詳細をログファイルで確認してください。",
  TaxonomyEditor_deletion_failed_title: "エラー",
  TaxonomyEditor_deletion_text: "選択したタグを削除してもよろしいですか？",
  TaxonomyEditor_deletion_text_referrer_warning: "選択したタグまたはその子は、まだ{0}コンテンツにリンクしています。<br/><br/>選択したタグを削除してもよろしいですか？",
  TaxonomyEditor_deletion_title: "タグを削除",
  TaxonomyEditor_title: "タグ",
  TaxonomyExplorerPanel_add_button_label: "子タグを追加する",
  TaxonomyExplorerPanel_reload_button_label: "タグをリロードする",
  TaxonomyExplorerPanel_remove_button_label: "選択したタグを削除",
  TaxonomyExplorerPanel_cut_button_label: "タグの切り取り",
  TaxonomyExplorerPanel_delete_button_label: "タグを削除",
  TaxonomyExplorerPanel_paste_button_label: "タグの貼り付け",
  TaxonomyExplorerColumn_emptyText_loading: "タグのロード中…",
  TaxonomyExplorerColumn_emptyText_no_keywords: "タグは見つかりませんでした。",
  TaxonomyExplorerColumn_undefined: "未定義の",
  TaxonomyPreferences_option_name: "候補",
  TaxonomyPreferences_tab_title: "タグ",
  TaxonomyPreferences_value_nameMatching_text: "名前の一致",
  TaxonomyPreferences_value_semantic_opencalais_text: "セマンティック評価(OpenCalais)",
  TaxonomyPreferences_settings_tooltip: "候補設定では、所与のコンテンツでタグを見つける時に行われる､評価のタイプを定義します。",
  TaxonomySuggestions_empty_text: "一致する候補は見つかりませんでした。",
  TaxonomySuggestions_loading: "提案をロード中…",
  TaxonomyLinkList_add_suggestion_action_text: "タグを追加",
  TaxonomyLinkList_edit_action_text: "タグで表示",
  TaxonomyLinkList_empty_chooser_text: "以下のリストからタグを追加",
  TaxonomyLinkList_keyword_remove_text: "タグの削除",
  TaxonomyLinkList_singleSelection_title: "選択されたタグ",
  TaxonomyLinkList_status_loading_text: "ロード中…",
  TaxonomyLinkList_suggestions_add_all: "すべてを追加",
  TaxonomyLinkList_suggestions_reload: "候補をリロード",
  TaxonomyLinkList_suggestions_title: "候補のタグ",
  TaxonomyLinkList_title: "選択されたタグ",
  TaxonomyLinkList_contextMenu_chooseTag: "タグを選ぶ",
  Taxonomy_action_tooltip: "タグを選ぶ",
  taxonomy_selection_dialog_title: "タグを選ぶ",
  TaxonomyType_Location_text: "場所タグ",
  TaxonomyType_Subject_text: "主題タグ",
  TaxonomyChooser_selection_text: "使用できるすべてのタグをブラウズ",
  TaxonomyChooser_search_tag_title: "検索",
  TaxonomyChooser_search_tag_emptyText: "タグを検索…",
  Favbar_taxonomies_button_label: "タグ",
  Location: "場所",
  Subject: "主題",
});
