#!/usr/bin/env bash
set -ex

# determine were we are
# use $BASH_SOURCE[0] to be safe when script is insource
DIR=$(dirname "${BASH_SOURCE[0]}")

if [[ -e /opt/chefdk/bin/chef ]]; then
  echo "Found chefdk:"
  /opt/chefdk/bin/chef --version
  eval "$(/opt/chefdk/bin/chef shell-init bash)"
  cp ${DIR}/chefdk/Gemfile* ./
  chef gem install -g -N --minimal-deps --conservative --lock
else
  echo "you need to install chef-dk first, see prerequisites"
  exit 1
fi

set +e
vagrant_installation=$(which vagrant)
set -e
if [[ -x "${vagrant_installation}" ]]; then
  echo "using vagrant installation from ${vagrant_installation}"
else
  echo "faking vagrant installation for testkitchen"
  echo "echo Vagrant 1.8.1" > /tmp/vagrant
  chmod u+x /tmp/vagrant
  # should exists
  sudo mkdir -p /usr/local/bin
  sudo mv /tmp/vagrant /usr/local/bin/vagrant
fi