import ResourceBundleUtil from "@jangaroo/runtime/l10n/ResourceBundleUtil";
import PersonalizationPlugIn_properties from "./PersonalizationPlugIn_properties";

/**
 * Overrides of ResourceBundle "PersonalizationPlugIn" for Locale "ja".
 * @see PersonalizationPlugIn_properties#INSTANCE
 */
ResourceBundleUtil.override(PersonalizationPlugIn_properties, {
  segments_btn: "セグメント",
  profiles_btn: "テストユーザー",
  Tab_test_user_profile_raw_title: "基本設定",
  Tab_test_user_profile_struct_title: "拡張設定",
  openProfileDebugger_tooltip: "プロファイル情報を表示する",
  openProfileDebugger_text: "プロファイル詳細",
  group_header_label_site_specific: "サイト特有の",
  group_header_label_system_specific: "システム特有の",
  con_day_week_lt: "前に",
  con_day_week_eq: "その日に",
  con_day_week_gt: "後に",
  con_user_is_logged_in: "ログインしているユーザー",
  con_name: "名前",
  con_given_name: "名前",
  con_family_name: "名字",
  con_segment: "セグメント",
  con_keywords: "キーワード",
  con_explicit_interest: "明示的興味",
  con_sunday: "日曜日",
  con_monday: "月曜日",
  con_tuesday: "火曜日",
  con_wednesday: "水曜日",
  con_thursday: "木曜日",
  con_friday: "金曜日",
  con_saturday: "土曜日",
  con_referrer: "リファラーURL",
  con_query: "検索クエリ",
  con_searchengine: "検索エンジン",
  con_explicit_adaptive: "適応できるウェブサイト",
  con_explicit_social: "Elastic Social",
  con_explicit_mobile: "モバイル配送",
  con_explicit_multitouch: "マルチタッチポイント",
  con_social_background: "ユーザー",
  con_social_background_login: "ログインしているユーザー",
  con_number_of_comments: "コメントの数",
  con_number_of_ratings: "評価の数",
  con_number_of_likes: "いいね！の数",
  con_number_of_explicit_interests: "明示的な興味の数",
  con_gender: "性別",
  con_gender_male: "男",
  con_gender_female: "女",
  ARGUMENT_VALUE: "機能 '{0}' のパラメーター '{1}' の値が無効です。正しいタイプを使用しましたか？",
  ARGUMENT_UNKNOWN: "この機能 '{0}' では、パラメーター '{1}' は不明です",
  ARGUMENT_MISSING: "この機能 '{0}' にはパラメーター '{1}'が必要です",
  ARGUMENT_SYNTAX: "機能 '{0}' の引数 '{1}' は無効なシンタックスです。シンタックス&lt;名前&gt;:&lt;値&gt;を使用してください",
  FUNCTION_EVALUATION: "機能 '{0}' を評価している時に以下のエラーが発生しました。{1}",
  FUNCTION_UNKNOWN: "機能 '{0}' は不明です",
  GENERAL: "以下のエラーが発生しました。 '{0}'",
  p13n_context_taxonomy_explicit_interests_label: "明示的興味",
  p13n_context_taxonomy_implicit_interests_label: "暗黙的興味",
  p13n_context_taxonomy_add_subject_taxonomy_button_text: "+ キーワードを追加",
  p13n_context_explicit: "明示的興味",
  p13n_context_subjectTaxonomies: "主題タグ",
  p13n_context_locationTaxonomies: "場所タグ",
  p13_es_check: "ソーシャル",
  plugin_addHomeFolderContexts_suffix: " (プライベート)",
  p13n_tabs_interests: "興味",
});
